Cura 9365 fix building cura main
Ultimaker/conan-ultimaker-index pull request #1
Opened 2022-06-18 17:22 UTC by jellespijker

Added an UMBaseConanfile which is reused over our in source conan recipes. Such as Cura, Uranium, CuraEngine
Contains a function to obtain the version specific `conan_data` out of `conandata.yml`

Although not visible in the diff since they are on main already but Checkout the recipes:
- cpython
  - Use our own mpdecimal recipe.
  - Added version 3.10.4 specific patches and download sources to the conandata.yml
- mpdecimal
  - The recipe had trouble compiling on Windows, since it needed autotools, which was automatically executed on the mingw bash. This failed on  our computers. The easiest solution was to remove that logic. Now it just builds on the powershell.

2022-06-29 11:38 UTC, Ghostkeeper requested changes

2022-06-29 11:38 UTC, Ghostkeeper commented on recipes/sipbuildtool/conanfile.py
> +class SipBuildTool(object):
In Python3, this is equivalent to:
```suggestion
class SipBuildTool:
```

2022-06-29 11:38 UTC, Ghostkeeper commented on recipes/sipbuildtool/conanfile.py
> +        self.python_venv_interpreter = None
Maybe this should just be a local variable in the `configure` function? That's the only place where it's used.

2022-07-12 12:50 UTC, Joeydelarago requested changes

2022-07-12 12:50 UTC, Joeydelarago commented on recipes/sipbuildtool/conanfile.py
> +        self.conanfile.run(f"""{python_interpreter} -m venv {self._venv_base_path}""", env = "conanbuild")
```suggestion
        self.conanfile.run(f"{python_interpreter} -m venv {self._venv_base_path}", env = "conanbuild")
```

I don't think these multiline quotes are needed.

2022-07-12 12:50 UTC, Joeydelarago commented on recipes/sipbuildtool/conanfile.py
> +            self.conanfile.run(f"""{self.python_venv_interpreter} -m pip install wheel setuptools""", run_environment = True,
```suggestion
            self.conanfile.run(f"{self.python_venv_interpreter} -m pip install wheel setuptools", run_environment = True,
```

Same as above

2022-07-12 12:50 UTC, Joeydelarago commented on recipes/umbase/conanfile.py
> +            version = str(satifying_versions[-1])
```suggestion
            satifying_versions = [v for v in all_versions if v <= recipe_version]
            if len(satifying_versions) == 0:
                raise ConanException(f"Could not find a maximum satisfying version for {recipe_version} in {[str(v) for v in all_versions]}")
            version = str(max(satifying_versions))
```

I think something like this makes your intention a bit clearer

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +        self.sip_build_executable = None
For these python properties I like for them to be typed as it makes it easier to read/maintain

```suggestion
        self.conanfile: ConanFile = conanfile
        env = VirtualRunEnv(self.conanfile)
        self.run_env: Environment = env.environment()
        self.envvars: Optional[EnvVars] = None
        self.python_venv_interpreter: Optional[Path] = None
        self.sip_build_executable: Optional[Path] = None
```

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +        return os.path.join(self._venv_base_path, "bin")
```suggestion
        is_windows = self.conanfile.settings.os == "Windows"
        return os.path.join(self._venv_base_path, "Scripts" if is_windows else "bin")
```

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +            python_interpreter = Path(*[f'"{p}"' if " " in p else p for p in python_interpreter.parts])
Paths without spaces will work fine with or without quotes around. I the code becomes more readable if the quotes are removed
```suggestion
            python_interpreter = Path(*[f'"{p}"' for p in python_interpreter.parts])
```

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +                                                Path(sys.executable).stem + Path(sys.executable).suffix)
Why not use the `name` property here?

```suggestion
                                                Path(sys.executable).name)
```

https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name it seems to do the same as https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem + https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffix

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +            self.python_venv_interpreter = Path(*[f'"{p}"' if " " in p else p for p in self.python_venv_interpreter.parts])
```suggestion
            self.python_venv_interpreter = Path(*[f'"{p}"' for p in self.python_venv_interpreter.parts])
```

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +            build_dir = os.path.join(self.conanfile.build_folder, module_name).replace("\\", "\\\\")))
Just out of interest, why do we want to append `\\` to every existing `\\` ?

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +            self.sip_build_executable = Path(*[f'"{p}"' if " " in p else p for p in self.sip_build_executable.parts])
```suggestion
            self.sip_build_executable = Path(*[f'"{p}"' for p in self.sip_build_executable.parts])
```

2022-07-12 12:51 UTC, casperlamboo commented on recipes/sipbuildtool/conanfile.py
> +            f"{self.python_venv_interpreter} -c {outer}import sysconfig; print(sysconfig.get_path({inner}purelib{inner})){outer}",
is it not possible to escape the quotes rather then switching  the inner and outer quotes?

2022-07-12 12:51 UTC, casperlamboo commented on recipes/umbase/conanfile.py
> +            py_venv_interp = Path(*[f'"{p}"' if " " in p else p for p in py_venv_interp.parts])
```suggestion
            py_venv_interp = Path(*[f'"{p}"' for p in py_venv_interp.parts])
```

2022-07-12 12:51 UTC, casperlamboo commented on recipes/umbase/conanfile.py
> +            py_interp = Path(*[f'"{p}"' if " " in p else p for p in py_interp.parts])
```suggestion
            py_interp = Path(*[f'"{p}"' for p in py_interp.parts])
```

2022-07-12 12:51 UTC, casperlamboo commented on recipes/umbase/conanfile.py
> +                py_venv_interp = Path(*[f'"{p}"' if " " in p else p for p in py_venv_interp.parts])
```suggestion
                py_venv_interp = Path(*[f'"{p}"' for p in py_venv_interp.parts])
```

2022-07-12 12:55 UTC, jellespijker commented on recipes/umbase/conanfile.py
> +            version = str(satifying_versions[-1])
I'm not sure if `tools.Version` plays well with python `max()` should be since I uses also use `sorted` and that also uses the comparators, so it should to work with `max`

2022-07-12 12:59 UTC, jellespijker commented on recipes/sipbuildtool/conanfile.py
> +        self.sip_build_executable = None
Yes agree, for developers that wrote a dependency manager for a strong type language C++, they sure don't use `typing` something I followed along with (mostly, but not consistently) since I wanted to mimic their style as much as possible to not introduce unknown behavior.
Which is a real possibility since they do some wonkey-things with inheritance with Conan python_requires.

But I'm confident enough to allow for these typings, provided that the imports at the top of this files are also there

2022-07-12 13:01 UTC, jellespijker commented on recipes/sipbuildtool/conanfile.py
> +        return os.path.join(self._venv_base_path, "bin")
wauw you saved a whole line ;-) Nah kidding. Looks cleaner, will commit this. Probably a left over of some more elaborate except cases.

2022-07-12 13:53 UTC, jellespijker commented on recipes/sipbuildtool/conanfile.py
> +            python_interpreter = Path(*[f'"{p}"' if " " in p else p for p in python_interpreter.parts])
**Touch this at your own peril**
Somehow windows PowerShell and python do weird things together.

It took me ages to handle those paths correctly and shell and OS agnostic and it is a hell of a process to get this correct over 3 OSes and two different shell languages 

https://cpplang.slack.com/archives/C41CWV9HA/p1654942697502539?thread_ts=1654942697.502539&cid=C41CWV9HA

2022-07-13 12:57 UTC, merged